FROM node:24-alpine

WORKDIR /app

# Copy built .next folder
COPY .next ./next/
COPY public ./public/
COPY package.json package-lock.json ./
COPY .env.production ./

# Install production dependencies only
RUN npm ci --production

# Expose port
EXPOSE 3000

# Start app
CMD ["node", ".next/standalone/server.js"]
